#ifndef QP_POST_DEFS_H
#define QP_POST_DEFS_H

#include <stdint.h>

#define QP_POST_SERVER_COUNT 2U
#define QP_POST_QPS_PER_SERVER 64U
#define QP_POST_TOTAL_QPS (QP_POST_SERVER_COUNT * QP_POST_QPS_PER_SERVER)
#define QP_POST_MAX_PAYLOAD 1024U
#define QP_POST_DEFAULT_PORT 18515U
#define QP_POST_POLL_NS 10000L
#define QP_POST_DPA_COMP_QUEUE_DEPTH 8U
#define QP_POST_DPA_DRAIN_TIMEOUT_US 1000000ULL

#define QP_POST_DPA_STATUS_OK 0U
#define QP_POST_DPA_STATUS_BAD_COMPLETION 1U
#define QP_POST_DPA_STATUS_DRAIN_TIMEOUT 2U

#endif
