#ifndef QP_POST_DEFS_H
#define QP_POST_DEFS_H

#include <stdint.h>

#define QP_POST_SERVER_COUNT 2U
#define QP_POST_QPS_PER_SERVER 64U
#define QP_POST_TOTAL_QPS (QP_POST_SERVER_COUNT * QP_POST_QPS_PER_SERVER)
#define QP_POST_MAX_PAYLOAD 1024U
#define QP_POST_DEFAULT_PORT 18515U
#define QP_POST_DEFAULT_DEPTH 8U
#define QP_POST_MAX_DEPTH 128U
#define QP_POST_POLL_NS 10000L
#define QP_POST_DEFAULT_DPA_COMP_QUEUE_DEPTH (2U * QP_POST_MAX_DEPTH)
#define QP_POST_DPA_DRAIN_TIMEOUT_US 1000000ULL

#ifndef QP_POST_DPA_THREAD_COUNT
#define QP_POST_DPA_THREAD_COUNT 1U
#endif

#if QP_POST_DPA_THREAD_COUNT == 0U
#error "QP_POST_DPA_THREAD_COUNT must be at least 1"
#endif

#if QP_POST_DPA_THREAD_COUNT > QP_POST_TOTAL_QPS
#error "QP_POST_DPA_THREAD_COUNT cannot exceed QP_POST_TOTAL_QPS"
#endif

#if ((QP_POST_DPA_THREAD_COUNT & (QP_POST_DPA_THREAD_COUNT - 1U)) != 0U)
#error "QP_POST_DPA_THREAD_COUNT must be a power of two"
#endif

#if ((QP_POST_TOTAL_QPS % QP_POST_DPA_THREAD_COUNT) != 0U)
#error "QP_POST_TOTAL_QPS must be divisible by QP_POST_DPA_THREAD_COUNT"
#endif

#define QP_POST_DPA_QPS_PER_THREAD (QP_POST_TOTAL_QPS / QP_POST_DPA_THREAD_COUNT)
#define QP_POST_DPA_THREAD_DATA_ALIGNMENT 64U

#define QP_POST_DPA_STATUS_OK 0U
#define QP_POST_DPA_STATUS_BAD_COMPLETION 1U
#define QP_POST_DPA_STATUS_DRAIN_TIMEOUT 2U

#endif
